CREATE SCHEMA IF NOT EXISTS stg;

CREATE TABLE IF NOT EXISTS stg.wb_orders (
    srid TEXT PRIMARY KEY,
    date TIMESTAMPTZ,
    last_change_date TIMESTAMPTZ,
    supplier_article TEXT,
    tech_size TEXT,
    barcode TEXT,
    total_price NUMERIC(14, 2),
    discount_percent NUMERIC(6, 2),
    warehouse_name TEXT,
    oblast TEXT,
    income_id BIGINT,
    odid BIGINT,
    nm_id BIGINT,
    subject TEXT,
    category TEXT,
    brand TEXT,
    is_cancel BOOLEAN DEFAULT FALSE,
    cancel_dt TIMESTAMPTZ,
    price_with_disc NUMERIC(14, 2),
    finished_price NUMERIC(14, 2),
    source_loaded_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS stg.wb_sales (
    sale_id TEXT PRIMARY KEY,
    date TIMESTAMPTZ,
    last_change_date TIMESTAMPTZ,
    supplier_article TEXT,
    tech_size TEXT,
    barcode TEXT,
    total_price NUMERIC(14, 2),
    discount_percent NUMERIC(6, 2),
    is_supply BOOLEAN DEFAULT FALSE,
    is_realization BOOLEAN DEFAULT FALSE,
    promo_code_discount NUMERIC(14, 2),
    warehouse_name TEXT,
    country_name TEXT,
    oblast_okrug_name TEXT,
    region_name TEXT,
    income_id BIGINT,
    odid BIGINT,
    spp NUMERIC(8, 2),
    for_pay NUMERIC(14, 2),
    finished_price NUMERIC(14, 2),
    price_with_disc NUMERIC(14, 2),
    nm_id BIGINT,
    subject TEXT,
    category TEXT,
    brand TEXT,
    is_storno BOOLEAN DEFAULT FALSE,
    source_loaded_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS stg.wb_stocks (
    id BIGSERIAL PRIMARY KEY,
    warehouse_name TEXT,
    supplier_article TEXT,
    nm_id BIGINT,
    barcode TEXT,
    quantity INT,
    in_way_to_client INT,
    in_way_from_client INT,
    quantity_full INT,
    category TEXT,
    subject TEXT,
    brand TEXT,
    tech_size TEXT,
    price NUMERIC(14, 2),
    discount NUMERIC(6, 2),
    is_supply BOOLEAN DEFAULT FALSE,
    is_realization BOOLEAN DEFAULT FALSE,
    source_loaded_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS stg.wb_finance_detail (
    rrd_id BIGINT PRIMARY KEY,
    realizationreport_id BIGINT,
    nm_id BIGINT,
    sa_name TEXT,
    barcode TEXT,
    subject_name TEXT,
    brand_name TEXT,
    doc_type_name TEXT,
    supplier_oper_name TEXT,
    order_dt TIMESTAMPTZ,
    sale_dt TIMESTAMPTZ,
    rr_dt TIMESTAMPTZ,
    quantity INT DEFAULT 0,
    retail_amount NUMERIC(14, 2) DEFAULT 0,
    retail_price_withdisc_rub NUMERIC(14, 2) DEFAULT 0,
    ppvz_sales_commission NUMERIC(14, 2) DEFAULT 0,
    ppvz_for_pay NUMERIC(14, 2) DEFAULT 0,
    delivery_rub NUMERIC(14, 2) DEFAULT 0,
    storage_fee NUMERIC(14, 2) DEFAULT 0,
    penalty NUMERIC(14, 2) DEFAULT 0,
    additional_payment NUMERIC(14, 2) DEFAULT 0,
    acceptance NUMERIC(14, 2) DEFAULT 0,
    acquiring_fee NUMERIC(14, 2) DEFAULT 0,
    ppvz_reward NUMERIC(14, 2) DEFAULT 0,
    ppvz_vw NUMERIC(14, 2) DEFAULT 0,
    ppvz_vw_nds NUMERIC(14, 2) DEFAULT 0,
    deduction NUMERIC(14, 2) DEFAULT 0,
    rebill_logistic_cost NUMERIC(14, 2) DEFAULT 0,
    office_name TEXT,
    srid TEXT,
    gi_id BIGINT,
    source_loaded_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- --- Рекламные кампании (Promotion API) --- --
CREATE TABLE IF NOT EXISTS stg.wb_ads_daily (
    ads_date DATE NOT NULL,
    campaign_id BIGINT NOT NULL,
    nm_id BIGINT NOT NULL DEFAULT 0,
    views INT NOT NULL DEFAULT 0,
    clicks INT NOT NULL DEFAULT 0,
    ctr NUMERIC(8, 4) DEFAULT 0,
    cpc NUMERIC(14, 2) DEFAULT 0,
    spend NUMERIC(14, 2) NOT NULL DEFAULT 0,
    atbs INT NOT NULL DEFAULT 0,
    orders_count INT NOT NULL DEFAULT 0,
    shks INT NOT NULL DEFAULT 0,
    sum_price NUMERIC(14, 2) DEFAULT 0,
    source_loaded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (ads_date, campaign_id, nm_id)
);
